name       : vdpauinfo
version    : 1.0
release    : 3
source     :
    - https://people.freedesktop.org/~aplattner/vdpau/vdpauinfo-1.0.tar.gz : 4054960b7ae618c351ff1ce3e7831b5cbda964ae1fbf9969b7146404d3044bc4
license    : MIT
component  : system.utils
summary    : Command line utility for querying the capabilities of a VDPAU device
description: |
    Command line utility for querying the capabilities of a VDPAU device
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(vdpau)
setup      : |
    %patch -p1 < $pkgfiles/add-support-for-4-4-4-surface-formats.patch
    %patch -p1 < $pkgfiles/Add-support-for-vp9-info.patch
    %configure
build      : |
    %make
install    : |
    %make_install
