name       : vdpauinfo
version    : '1.4'
release    : 4
source     :
    - https://gitlab.freedesktop.org/vdpau/vdpauinfo/uploads/8f047eac351672cc4316724edb6ad2b2/vdpauinfo-1.4.tar.gz : 40188bc5671c139e58330dbcac2a6ced0064485cb4cdf368558feca17d7922a0
license    : MIT
component  : system.utils
summary    : Command line utility for querying the capabilities of a VDPAU device
description: |
    Command line utility for querying the capabilities of a VDPAU device
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(vdpau)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
